spring:
  datasource:
    url: jdbc:mysql://localhost:3306/block_db
    username: root
    password: Charansingh16@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Blockchain credential
b-lock:
  chain:
    rpcUrl: "https://polygon-amoy.infura.io/v3/2321a64be7934226b329b91595d3be23" #devansh
    privateKey: 6f50b4b221a8846feb0d9e3e3558f3deb339e63aa5f3efcbb542ec2c12e7afd4 #devansh
    registryAddress: "0xE5eDDD5EAB832a246fAC0961C8B72cc72DF7fF87" #armaan
