/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "byHash"
      | "isInstitution"
      | "issueCredential"
      | "owner"
      | "setInstitution"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialIssued" | "InstitutionToggled"
  ): EventFragment;

  encodeFunctionData(functionFragment: "byHash", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isInstitution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setInstitution",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "verify", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "byHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    fileHash: BytesLike,
    issuer: AddressLike,
    student: AddressLike,
    issuedAt: BigNumberish
  ];
  export type OutputTuple = [
    fileHash: string,
    issuer: string,
    student: string,
    issuedAt: bigint
  ];
  export interface OutputObject {
    fileHash: string;
    issuer: string;
    student: string;
    issuedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionToggledEvent {
  export type InputTuple = [inst: AddressLike, enabled: boolean];
  export type OutputTuple = [inst: string, enabled: boolean];
  export interface OutputObject {
    inst: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: CredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  byHash: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        issuer: string;
        student: string;
        fileHash: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;

  isInstitution: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  issueCredential: TypedContractMethod<
    [fileHash: BytesLike, student: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setInstitution: TypedContractMethod<
    [inst: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<
    [fileHash: BytesLike],
    [
      [boolean, string, string, bigint] & {
        exists: boolean;
        issuer: string;
        student: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "byHash"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        issuer: string;
        student: string;
        fileHash: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInstitution"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [fileHash: BytesLike, student: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setInstitution"
  ): TypedContractMethod<
    [inst: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [fileHash: BytesLike],
    [
      [boolean, string, string, bigint] & {
        exists: boolean;
        issuer: string;
        student: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionToggled"
  ): TypedContractEvent<
    InstitutionToggledEvent.InputTuple,
    InstitutionToggledEvent.OutputTuple,
    InstitutionToggledEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(bytes32,address,address,uint64)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "InstitutionToggled(address,bool)": TypedContractEvent<
      InstitutionToggledEvent.InputTuple,
      InstitutionToggledEvent.OutputTuple,
      InstitutionToggledEvent.OutputObject
    >;
    InstitutionToggled: TypedContractEvent<
      InstitutionToggledEvent.InputTuple,
      InstitutionToggledEvent.OutputTuple,
      InstitutionToggledEvent.OutputObject
    >;
  };
}
